// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	albumTracks: (albumId: number) => typedError<Track[], AppErrorDto>(__TAURI_INVOKE("album_tracks", { albumId })),
	albumsQuery: () => typedError<AlbumInfo[], AppErrorDto>(__TAURI_INVOKE("albums_query")),
	artistTracks: (artistId: number) => typedError<Track[], AppErrorDto>(__TAURI_INVOKE("artist_tracks", { artistId })),
	artistsQuery: () => typedError<ArtistInfo[], AppErrorDto>(__TAURI_INVOKE("artists_query")),
	/**  导出全量备份到 JSON 文件，返回各部分计数（设置页展示用） */
	backupExport: (path: string) => typedError<BackupExportResult, AppErrorDto>(__TAURI_INVOKE("backup_export", { path })),
	/**
	 *  从 JSON 文件恢复备份（合并语义），返回恢复报告；
	 *  设置恢复后即时重注册各全局快捷键（覆盖"新环境恢复"场景，无需重启）
	 */
	backupRestore: (path: string) => typedError<BackupRestoreResult, AppErrorDto>(__TAURI_INVOKE("backup_restore", { path })),
	coverPath: (file: string) => typedError<string | null, AppErrorDto>(__TAURI_INVOKE("cover_path", { file })),
	/**  清理重复项：源文件移入回收站成功后删除曲库记录（级联清 歌单曲目/收藏/播放历史） */
	duplicateResolve: (keepId: number, removeIds: number[]) => typedError<DuplicateResolve, AppErrorDto>(__TAURI_INVOKE("duplicate_resolve", { keepId, removeIds })),
	duplicatesScan: () => typedError<DuplicateGroup[], AppErrorDto>(__TAURI_INVOKE("duplicates_scan")),
	favoriteToggle: (trackId: number) => typedError<boolean, AppErrorDto>(__TAURI_INVOKE("favorite_toggle", { trackId })),
	/**  收藏 id 集合（前端行内红心状态用，避免逐行查询） */
	favoritesIds: () => typedError<number[], AppErrorDto>(__TAURI_INVOKE("favorites_ids")),
	favoritesList: () => typedError<Track[], AppErrorDto>(__TAURI_INVOKE("favorites_list")),
	/**
	 *  拖拽导入（M7）：目录直接作为曲库来源；音频文件取其所在目录——曲库以目录为管理单元
	 *  （tracks.folder_id 非空 + 增量监听按目录），单文件导入无法纳入监听与删除联动。
	 *  已被现有曲库目录或本次候选覆盖的范围跳过，避免重复扫描。
	 */
	dropImport: (paths: string[]) => typedError<DropImportResult, AppErrorDto>(__TAURI_INVOKE("drop_import", { paths })),
	folderAdd: (path: string) => typedError<Folder, AppErrorDto>(__TAURI_INVOKE("folder_add", { path })),
	folderList: () => typedError<Folder[], AppErrorDto>(__TAURI_INVOKE("folder_list")),
	folderRemove: (id: number) => typedError<boolean, AppErrorDto>(__TAURI_INVOKE("folder_remove", { id })),
	folderTracks: (folderId: number) => typedError<Track[], AppErrorDto>(__TAURI_INVOKE("folder_tracks", { folderId })),
	historyAdd: (trackId: number) => typedError<null, AppErrorDto>(__TAURI_INVOKE("history_add", { trackId })),
	libraryRescan: () => typedError<null, AppErrorDto>(__TAURI_INVOKE("library_rescan")),
	lyricsGet: (trackId: number) => typedError<string | null, AppErrorDto>(__TAURI_INVOKE("lyrics_get", { trackId })),
	overlayHide: () => typedError<null, AppErrorDto>(__TAURI_INVOKE("overlay_hide")),
	/**  锁定⇄调整态（锁定 = 鼠标完全穿透） */
	overlaySetLocked: (locked: boolean) => typedError<null, AppErrorDto>(__TAURI_INVOKE("overlay_set_locked", { locked })),
	/**  透明度调节 0.3–0.9，即时生效并持久化 */
	overlaySetOpacity: (opacity: number | null) => typedError<null, AppErrorDto>(__TAURI_INVOKE("overlay_set_opacity", { opacity })),
	/**  配置调整/锁定切换的全局快捷键（设置页调用，即时生效并持久化） */
	overlaySetShortcut: (shortcut: string) => typedError<null, AppErrorDto>(__TAURI_INVOKE("overlay_set_shortcut", { shortcut })),
	/**  显示/隐藏迷你悬浮窗（托盘与主窗口播放条共用入口） */
	overlayToggle: () => typedError<null, AppErrorDto>(__TAURI_INVOKE("overlay_toggle")),
	playlistAddTracks: (id: number, trackIds: number[]) => typedError<number, AppErrorDto>(__TAURI_INVOKE("playlist_add_tracks", { id, trackIds })),
	playlistCreate: (name: string) => typedError<Playlist, AppErrorDto>(__TAURI_INVOKE("playlist_create", { name })),
	playlistDelete: (id: number) => typedError<null, AppErrorDto>(__TAURI_INVOKE("playlist_delete", { id })),
	/**  导出歌单为 UTF-8 M3U8 文件（绝对路径，foobar2000 兼容），返回写入曲目数 */
	playlistExport: (id: number, path: string) => typedError<number, AppErrorDto>(__TAURI_INVOKE("playlist_export", { id, path })),
	/**  从 M3U8 文件导入为新歌单，返回 新歌单id/导入数/跳过数 */
	playlistImport: (path: string, name: string) => typedError<PlaylistImport, AppErrorDto>(__TAURI_INVOKE("playlist_import", { path, name })),
	playlistList: () => typedError<Playlist[], AppErrorDto>(__TAURI_INVOKE("playlist_list")),
	playlistRemoveTrack: (id: number, trackId: number) => typedError<number, AppErrorDto>(__TAURI_INVOKE("playlist_remove_track", { id, trackId })),
	playlistRename: (id: number, name: string) => typedError<null, AppErrorDto>(__TAURI_INVOKE("playlist_rename", { id, name })),
	playlistReorder: (id: number, trackIds: number[]) => typedError<number, AppErrorDto>(__TAURI_INVOKE("playlist_reorder", { id, trackIds })),
	playlistTracks: (id: number) => typedError<Track[], AppErrorDto>(__TAURI_INVOKE("playlist_tracks", { id })),
	scrapeAlbum: (albumId: number, source: 
/**  iTunes Search（JP 店面优先，US 兜底）：封面/专辑信息 */
"itunes" | 
/**  Deezer API：封面/专辑信息 */
"deezer" | 
/**  MusicBrainz + Cover Art Archive：专辑信息/封面（仅专辑模式，1 req/s 限速） */
"musicBrainz" | null, query: string | null) => typedError<AlbumCandidate[], AppErrorDto>(__TAURI_INVOKE("scrape_album", { albumId, source, query })),
	/**  应用专辑候选：封面入缓存 → albums.cover_file/year 更新 → 专辑内曲目的 year/genre 同步 */
	scrapeApplyAlbum: (albumId: number, candidate: AlbumCandidate) => typedError<string | null, AppErrorDto>(__TAURI_INVOKE("scrape_apply_album", { albumId, candidate })),
	/**  应用歌词候选：同步歌词优先；同名 .lrc 已存在时一并更新，保持两条通道一致 */
	scrapeApplyLyrics: (trackId: number, candidate: LyricsCandidate) => typedError<null, AppErrorDto>(__TAURI_INVOKE("scrape_apply_lyrics", { trackId, candidate })),
	/**  应用单曲候选：仅该曲目的封面（文本字段走标签编辑，职责分离） */
	scrapeApplyTrack: (trackId: number, candidate: AlbumCandidate) => typedError<string, AppErrorDto>(__TAURI_INVOKE("scrape_apply_track", { trackId, candidate })),
	scrapeLyrics: (trackId: number, query: string | null) => typedError<LyricsCandidate[], AppErrorDto>(__TAURI_INVOKE("scrape_lyrics", { trackId, query })),
	scrapeTrack: (trackId: number, source: 
/**  iTunes Search（JP 店面优先，US 兜底）：封面/专辑信息 */
"itunes" | 
/**  Deezer API：封面/专辑信息 */
"deezer" | 
/**  MusicBrainz + Cover Art Archive：专辑信息/封面（仅专辑模式，1 req/s 限速） */
"musicBrainz" | null, query: string | null) => typedError<AlbumCandidate[], AppErrorDto>(__TAURI_INVOKE("scrape_track", { trackId, source, query })),
	searchTracks: (q: string, page: number | null, pageSize: number | null) => typedError<TrackPage, AppErrorDto>(__TAURI_INVOKE("search_tracks", { q, page, pageSize })),
	settingsGet: (key: string) => typedError<string | null, AppErrorDto>(__TAURI_INVOKE("settings_get", { key })),
	settingsSet: (key: string, value: string) => typedError<null, AppErrorDto>(__TAURI_INVOKE("settings_set", { key, value })),
	/**
	 *  设置/清除播放控制类全局快捷键（M7，设置页调用）：
	 *  shortcut 为 None 或空串 = 清除绑定；注册失败返回错误并保持旧键可用
	 */
	shortcutSet: (action: string, shortcut: string | null) => typedError<null, AppErrorDto>(__TAURI_INVOKE("shortcut_set", { action, shortcut })),
	smartPlaylistCreate: (name: string, rules: SmartRule[], trackLimit: number | null) => typedError<SmartPlaylist, AppErrorDto>(__TAURI_INVOKE("smart_playlist_create", { name, rules, trackLimit })),
	smartPlaylistDelete: (id: number) => typedError<null, AppErrorDto>(__TAURI_INVOKE("smart_playlist_delete", { id })),
	smartPlaylistList: () => typedError<SmartPlaylist[], AppErrorDto>(__TAURI_INVOKE("smart_playlist_list")),
	smartPlaylistTracks: (id: number) => typedError<Track[], AppErrorDto>(__TAURI_INVOKE("smart_playlist_tracks", { id })),
	smartPlaylistUpdate: (id: number, name: string, rules: SmartRule[], trackLimit: number | null) => typedError<null, AppErrorDto>(__TAURI_INVOKE("smart_playlist_update", { id, name, rules, trackLimit })),
	/**
	 *  主窗口 → Rust：转发播放状态给系统媒体浮层（SMTC）；
	 *  非 Windows 平台为 no-op（本项目 Windows 优先，规范见技术设计文档 §6）
	 */
	smtcUpdate: (state: SmtcState) => typedError<null, AppErrorDto>(__TAURI_INVOKE("smtc_update", { state })),
	historyRecent: (limit: number | null) => typedError<Track[], AppErrorDto>(__TAURI_INVOKE("history_recent", { limit })),
	historyTop: (limit: number | null) => typedError<Track[], AppErrorDto>(__TAURI_INVOKE("history_top", { limit })),
	tagUpdate: (trackId: number, patch: TagPatch) => typedError<Track, AppErrorDto>(__TAURI_INVOKE("tag_update", { trackId, patch })),
	/**
	 *  批量标签编辑（M6）：留空字段=不修改（沿用现值），曲号重编按传入顺序起始号递增。
	 *  逐首 写回文件 → 曲库同步（各自事务）；单首失败不中断，返回 成功列表/失败数/首个错误。
	 */
	tagUpdateBatch: (trackIds: number[], patch: BatchTagPatch) => typedError<BatchTagResult, AppErrorDto>(__TAURI_INVOKE("tag_update_batch", { trackIds, patch })),
	trackGet: (id: number) => typedError<{
	id: number,
	path: string,
	title: string,
	artist: string | null,
	album: string | null,
	trackNo: number | null,
	durationSec: number | null,
	sampleRate: number | null,
	bitrate: number | null,
	year: number | null,
	genre: string | null,
	coverFile: string | null,
} | null, AppErrorDto>(__TAURI_INVOKE("track_get", { id })),
	tracksAll: () => typedError<Track[], AppErrorDto>(__TAURI_INVOKE("tracks_all")),
	tracksQuery: (page: number | null, pageSize: number | null, sort: string | null) => typedError<TrackPage, AppErrorDto>(__TAURI_INVOKE("tracks_query", { page, pageSize, sort })),
};

/* Types */
/**  iTunes 刮削候选（专辑/单曲封面与专辑信息，iTunes Search API） */
export type AlbumCandidate = {
	/**  来源店面："itunes-jp" | "itunes-us"（J-Pop 优先 JP 店面，US 兜底） */
	provider: string,
	name: string,
	artist: string,
	year: number | null,
	genre: string | null,
	trackCount: number | null,
	/**  高清封面 URL（artworkUrl100 替换为 1200x1200） */
	artworkUrl: string | null,
};

/**  专辑卡片（封面墙用，含曲目数） */
export type AlbumInfo = {
	id: number,
	name: string,
	artist: string,
	year: number | null,
	coverFile: string | null,
	trackCount: number,
};

/**  命令层错误 DTO（specta 类型生成要求 Type） */
export type AppErrorDto = {
	message: string,
};

/**  艺人条目（艺人视图用，含曲目/专辑数） */
export type ArtistInfo = {
	id: number,
	name: string,
	trackCount: number,
	albumCount: number,
};

export type BackupExportResult = {
	playlists: number,
	tracks: number,
	smartPlaylists: number,
	favorites: number,
	history: number,
};

/**  恢复报告：skipped 汇总所有按路径未命中曲库的引用（歌单曲目/收藏/历史） */
export type BackupRestoreResult = {
	playlistsCreated: number,
	/**  同名歌单合并追加曲目的个数 */
	playlistsMerged: number,
	playlistTracksAdded: number,
	smartPlaylistsCreated: number,
	/**  同名已存在或规则非法而跳过的智能歌单个数 */
	smartPlaylistsSkipped: number,
	favoritesAdded: number,
	historyAdded: number,
	tracksSkipped: number,
	settingsRestored: number,
};

/**
 *  批量标签编辑（M6）：None = 不修改该字段（区别于单曲编辑的 null=清除）；
 *  曲号重编 = track_no_start 起按传入顺序重编
 */
export type BatchTagPatch = {
	artist: string | null,
	album: string | null,
	genre: string | null,
	year: number | null,
	trackNoStart: number | null,
};

export type BatchTagResult = {
	updated: Track[],
	failed: number,
	firstError: string | null,
};

/**  拖拽导入（M7）：新增曲库目录数 / 跳过数（已被曲库目录覆盖或不支持的路径） */
export type DropImportResult = {
	foldersAdded: number,
	foldersSkipped: number,
};

/**  重复曲目组（M6）：items 按添加时间升序，items[0] 为保留候选 */
export type DuplicateGroup = {
	title: string,
	artist: string,
	items: DuplicateItem[],
};

export type DuplicateItem = {
	track: Track,
	/**  字节数（f64 承载，specta 禁 i64） */
	size: number | null,
	createdAt: string,
};

export type DuplicateResolve = {
	removed: number,
	failed: number,
	firstError: string | null,
};

/**  对外 DTO 统一用 i32/u32（specta-typescript 禁止 i64/u64 导出），DB 层内部仍用 i64 */
export type Folder = {
	id: number,
	path: string,
};

/**  LRCLIB 歌词候选（带完整文本，应用时整体回传落库） */
export type LyricsCandidate = {
	id: number,
	trackName: string,
	artistName: string,
	durationSec: number | null,
	instrumental: boolean,
	syncedLyrics: string | null,
	plainLyrics: string | null,
};

/**  歌单（侧边栏与歌单视图用） */
export type Playlist = {
	id: number,
	name: string,
	trackCount: number,
	createdAt: string,
};

/**  M3U8 导入结果：added 为按曲库匹配入库的曲目数，skipped 为未命中跳过数 */
export type PlaylistImport = {
	playlistId: number,
	added: number,
	skipped: number,
};

/**  刮削来源站点（免鉴权主流源）；None = 全部站点合并检索 */
export type ScrapeSource = 
/**  iTunes Search（JP 店面优先，US 兜底）：封面/专辑信息 */
"itunes" | 
/**  Deezer API：封面/专辑信息 */
"deezer" | 
/**  MusicBrainz + Cover Art Archive：专辑信息/封面（仅专辑模式，1 req/s 限速） */
"musicBrainz";

/**  智能歌单规则字段（功能设计文档 M4：五类规则） */
export type SmartField = 
/**  播放次数（play_history 聚合） */
"playCount" | 
/**  最近播放：最近 N 天内播过 */
"lastPlayed" | 
/**  流派（contains / equals） */
"genre" | 
/**  年份 */
"year" | 
/**  添加时间：最近 N 天内入库 */
"addedAt";

export type SmartOp = 
/**  数值/年份 ≥ */
"gte" | 
/**  数值/年份 ≤ */
"lte" | 
/**  流派等于 */
"eq" | 
/**  流派包含 */
"contains" | 
/**  时间字段：最近 N 天内 */
"withinDays";

/**  智能歌单（列表实时生成：smart_playlist_tracks 每次按 rules 现算） */
export type SmartPlaylist = {
	id: number,
	name: string,
	rules: SmartRule[],
	trackLimit: number | null,
	trackCount: number,
};

/**  单条规则：field + op + 数值或文本（二选一，按 field 语义取用） */
export type SmartRule = {
	field: SmartField,
	op: SmartOp,
	/**  数值条件（playCount / year / withinDays 的天数） */
	num: number | null,
	/**  文本条件（genre） */
	text: string | null,
};

/**  SMTC 转发载荷（主窗口 playerStore → Rust → 系统媒体浮层） */
export type SmtcState = {
	title: string,
	artist: string | null,
	isPlaying: boolean,
	positionSec: number | null,
	durationSec: number | null,
	coverFile: string | null,
};

/**  标签编辑（M4）：全字段整体提交，null = 清除该字段，写回源文件后同步曲库 */
export type TagPatch = {
	title: string,
	artist: string | null,
	album: string | null,
	genre: string | null,
	year: number | null,
	trackNo: number | null,
};

export type Track = {
	id: number,
	path: string,
	title: string,
	artist: string | null,
	album: string | null,
	trackNo: number | null,
	durationSec: number | null,
	sampleRate: number | null,
	bitrate: number | null,
	year: number | null,
	genre: string | null,
	coverFile: string | null,
};

export type TrackPage = {
	items: Track[],
	total: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

